import type { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "chicken-donburi",
    title: "간장 닭다리 덮밥",
    description: "닭다리살과 양파를 달큰한 간장 소스에 볶아 밥 위에 올려요.",
    mealSlots: ["점심", "저녁"],
    difficulty: 1,
    cookTime: 20,
    servings: 1,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
    imageAlt: "간장 소스를 곁들인 덮밥",
    tags: ["한 그릇", "초보 추천"],
    ingredients: [
      { ingredientId: "chicken-thigh", rawName: "닭다리살", quantity: 200, unit: "g", preparation: "한입 크기" },
      { ingredientId: "onion", rawName: "채 썬 양파", quantity: 0.5, unit: "개" },
      { ingredientId: "rice", rawName: "밥", quantity: 210, unit: "g" },
      { ingredientId: "green-onion", rawName: "송송 썬 대파", quantity: 20, unit: "g" },
      { ingredientId: "soy-sauce", rawName: "간장", quantity: 1, unit: "큰술" },
      { ingredientId: "garlic", rawName: "다진 마늘", quantity: 0.5, unit: "큰술" },
    ],
    steps: [
      "닭다리살에 간장과 다진 마늘을 가볍게 버무려요.",
      "팬을 달군 뒤 닭다리살을 노릇하게 익혀요.",
      "양파와 대파를 넣고 숨이 죽을 때까지 볶아요.",
      "밥 위에 올리고 남은 소스를 끼얹어요.",
    ],
  },
  {
    id: "tofu-kimchi",
    title: "두부 김치",
    description: "냉장고에 남은 김치와 두부로 빠르게 완성하는 든든한 한 접시예요.",
    mealSlots: ["점심", "저녁"],
    difficulty: 1,
    cookTime: 15,
    servings: 1,
    imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=900&q=80",
    imageAlt: "두부와 볶은 김치",
    tags: ["15분", "남은 재료"],
    ingredients: [
      { ingredientId: "tofu", rawName: "두부", quantity: 1, unit: "팩" },
      { ingredientId: "kimchi", rawName: "김치", quantity: 200, unit: "g" },
      { ingredientId: "onion", rawName: "양파", quantity: 0.25, unit: "개" },
      { ingredientId: "green-onion", rawName: "대파", quantity: 20, unit: "g" },
      { ingredientId: "sesame-oil", rawName: "참기름", quantity: 0.5, unit: "큰술" },
    ],
    steps: [
      "두부를 먹기 좋은 크기로 썰어 데워요.",
      "팬에 참기름을 두르고 양파와 대파를 볶아요.",
      "김치를 넣고 5분 정도 볶아 두부와 함께 담아요.",
    ],
  },
  {
    id: "tuna-mayo-rice",
    title: "참치마요 주먹밥",
    description: "참치캔과 밥, 김만 있으면 되는 간단한 아침 또는 도시락 메뉴예요.",
    mealSlots: ["아침", "점심"],
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=80",
    imageAlt: "김을 곁들인 주먹밥",
    tags: ["10분", "불 없이"],
    ingredients: [
      { ingredientId: "tuna", rawName: "참치캔", quantity: 1, unit: "팩" },
      { ingredientId: "rice", rawName: "밥", quantity: 210, unit: "g" },
      { ingredientId: "seaweed", rawName: "김", quantity: 2, unit: "장" },
      { ingredientId: "green-onion", rawName: "다진 대파", quantity: 10, unit: "g" },
      { ingredientId: "sesame-oil", rawName: "참기름", quantity: 0.5, unit: "큰술" },
    ],
    steps: [
      "참치캔의 기름을 빼고 밥과 섞어요.",
      "대파와 참기름을 넣고 고루 섞어요.",
      "김을 부숴 넣거나 겉에 묻혀 주먹밥을 만들어요.",
    ],
  },
  {
    id: "cabbage-egg-stir-fry",
    title: "양배추 계란 볶음",
    description: "양배추와 계란을 볶아 밥과 함께 먹는 가벼운 한 끼예요.",
    mealSlots: ["아침", "점심", "저녁"],
    difficulty: 1,
    cookTime: 12,
    servings: 1,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
    imageAlt: "채소와 계란 볶음",
    tags: ["냉장고 털기", "초보 추천"],
    ingredients: [
      { ingredientId: "cabbage", rawName: "채 썬 양배추", quantity: 150, unit: "g" },
      { ingredientId: "egg", rawName: "달걀", quantity: 2, unit: "개" },
      { ingredientId: "carrot", rawName: "당근", quantity: 50, unit: "g" },
      { ingredientId: "green-onion", rawName: "대파", quantity: 15, unit: "g" },
      { ingredientId: "soy-sauce", rawName: "간장", quantity: 0.5, unit: "큰술" },
    ],
    steps: [
      "양배추와 당근을 얇게 썰어요.",
      "팬에 대파를 볶아 향을 낸 뒤 양배추와 당근을 넣어요.",
      "계란을 넣고 반숙 정도로 섞은 뒤 간장으로 간해요.",
    ],
  },
  {
    id: "cucumber-tuna-bowl",
    title: "오이 참치 비빔밥",
    description: "아삭한 오이와 참치, 김을 밥에 올려 불을 거의 쓰지 않고 만들어요.",
    mealSlots: ["아침", "점심"],
    difficulty: 1,
    cookTime: 8,
    servings: 1,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
    imageAlt: "참치와 채소를 올린 밥",
    tags: ["8분", "남은 재료"],
    ingredients: [
      { ingredientId: "cucumber", rawName: "오이", quantity: 0.5, unit: "개" },
      { ingredientId: "tuna", rawName: "참치캔", quantity: 1, unit: "팩" },
      { ingredientId: "rice", rawName: "밥", quantity: 210, unit: "g" },
      { ingredientId: "seaweed", rawName: "김", quantity: 2, unit: "장" },
      { ingredientId: "gochujang", rawName: "고추장", quantity: 0.5, unit: "큰술" },
    ],
    steps: [
      "오이를 얇게 썰어요.",
      "밥 위에 오이와 참치를 올려요.",
      "김과 고추장을 곁들여 비벼 먹어요.",
    ],
  },
  {
    id: "kimchi-fried-rice",
    title: "김치 볶음밥",
    description: "남은 밥과 김치를 가장 빠르게 다음 한 끼로 바꾸는 메뉴예요.",
    mealSlots: ["아침", "점심", "저녁"],
    difficulty: 1,
    cookTime: 15,
    servings: 1,
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=80",
    imageAlt: "김치 볶음밥",
    tags: ["남은 밥", "15분"],
    ingredients: [
      { ingredientId: "rice", rawName: "밥", quantity: 210, unit: "g" },
      { ingredientId: "kimchi", rawName: "김치", quantity: 150, unit: "g" },
      { ingredientId: "egg", rawName: "계란", quantity: 1, unit: "개" },
      { ingredientId: "green-onion", rawName: "대파", quantity: 20, unit: "g" },
      { ingredientId: "sesame-oil", rawName: "참기름", quantity: 0.5, unit: "큰술" },
    ],
    steps: [
      "대파를 볶아 향을 내고 김치를 넣어요.",
      "밥을 넣고 김치와 고루 섞어 볶아요.",
      "계란을 곁들이고 참기름을 둘러 마무리해요.",
    ],
  },
];

export function getRecipe(recipeId: string): Recipe {
  const recipe = RECIPES.find((item) => item.id === recipeId);
  if (!recipe) throw new Error(`Unknown recipe: ${recipeId}`);
  return recipe;
}
